

--TODO: 
--remove dummy variables -> multicollinearity
--add other tables
--split into auto/home tables
--check subro_referral_flg difference in claim vs coverage table

database dl_vsuperus;

--Create table for prepared data
CREATE TABLE dl_T034847.ProcessedAutoClaims (
  CLAIM_ID varchar(72)
  --fields derived from CLAIM
  ,FILE_TYPE_IS_DEFERRED DECIMAL(17,0)
  ,FILE_TYPE_IS_REGULAR DECIMAL(17,0)
  ,FILE_TYPE_IS_SUBROGATION DECIMAL(17,0)
  ,DAYS_REPORTED_AFTER_LOSS DECIMAL(17,0)
  ,STATUS_IS_OPEN DECIMAL(17,0)
  ,STATUS_IS_CLOSED DECIMAL(17,0)
  ,SUBRO_REFERRAL_FLG DECIMAL(17,0)
  ,AT_FAULT_FLG DECIMAL(17,0)
  ,CATASTROPHE_FLG DECIMAL(17,0)
  ,REPORTED_BY_SELF DECIMAL(17,0)
  ,REPORTED_BY_CLAIMANT DECIMAL(17,0)
  ,REPORTED_BY_CHILD DECIMAL(17,0)
  ,REPORTED_BY_INS_CO DECIMAL(17,0)
  ,REPORTED_BY_OTHER DECIMAL(17,0)
  ,REPORTED_BY_SPOUSE DECIMAL(17,0)
  ,REPORTED_BY_RELATIVE DECIMAL(17,0)
  ,REPORTED_BY_ATTORNEY DECIMAL(17,0)
  ,REPORTED_BY_ADV_SUBRO_HNDLR DECIMAL(17,0)
  ,REPORTED_BY_CLAIMANT_ATTRNY DECIMAL(17,0)
  ,REPORTED_BY_PARENT DECIMAL(17,0)
  ,CLAIM_IN_POLICY_STATE DECIMAL(17,0)
  ,CLAIM_STATE_MA DECIMAL(17,0)
  ,CLAIM_STATE_TX DECIMAL(17,0)
  ,CLAIM_STATE_CT DECIMAL(17,0)
  ,CLAIM_STATE_NY DECIMAL(17,0)
  ,CLAIM_STATE_FL DECIMAL(17,0)
  ,CLAIM_STATE_RI DECIMAL(17,0)
  ,CLAIM_STATE_CA DECIMAL(17,0)
  ,CLAIM_STATE_NC DECIMAL(17,0)
  ,CLAIM_STATE_NJ DECIMAL(17,0)
  ,CLAIM_STATE_GA DECIMAL(17,0)
  ,CLAIM_STATE_CO DECIMAL(17,0)
  ,CLAIM_STATE_PA DECIMAL(17,0)
  ,CLAIM_STATE_NH DECIMAL(17,0)
  ,CLAIM_STATE_WA DECIMAL(17,0)
  ,CLAIM_STATE_MD DECIMAL(17,0)
  ,CLAIM_STATE_AZ DECIMAL(17,0)
  ,CLAIM_STATE_VA DECIMAL(17,0)
  ,CLAIM_STATE_OR DECIMAL(17,0)
  ,CLAIM_STATE_OH DECIMAL(17,0)
  ,CLAIM_STATE_IL DECIMAL(17,0)
  ,CLAIM_STATE_MI DECIMAL(17,0)
  ,CLAIM_STATE_MN DECIMAL(17,0)
  ,CLAIM_STATE_SC DECIMAL(17,0)
  ,CLAIM_STATE_TN DECIMAL(17,0)
  ,CLAIM_STATE_ME DECIMAL(17,0)
  ,LOSS_TYPE_1 DECIMAL(17,0)
  ,LOSS_TYPE_2 DECIMAL(17,0)
  ,LOSS_TYPE_3 DECIMAL(17,0)
  ,LOSS_TYPE_4 DECIMAL(17,0)
  ,LOSS_TYPE_5 DECIMAL(17,0)
  ,LOSS_TYPE_6 DECIMAL(17,0)
  ,LOSS_TYPE_7 DECIMAL(17,0)
  ,LOSS_TYPE_8 DECIMAL(17,0)
  ,LOSS_TYPE_9 DECIMAL(17,0)
  ,LOSS_TYPE_10 DECIMAL(17,0)
  ,LOSS_TYPE_11 DECIMAL(17,0)
  ,LOSS_TYPE_12 DECIMAL(17,0)
  ,LOSS_TYPE_13 DECIMAL(17,0)
  ,LOSS_TYPE_14 DECIMAL(17,0)
  ,LOSS_TYPE_15 DECIMAL(17,0)
  ,LOSS_TYPE_16 DECIMAL(17,0)
  ,LOSS_TYPE_17 DECIMAL(17,0)
  ,LOSS_TYPE_18 DECIMAL(17,0)
  ,LOSS_TYPE_19 DECIMAL(17,0)
  ,LOSS_TYPE_20 DECIMAL(17,0)
  ,LOSS_TYPE_21 DECIMAL(17,0)
  ,LOSS_TYPE_22 DECIMAL(17,0)
  ,LOSS_TYPE_23 DECIMAL(17,0)
  ,LOSS_TYPE_24 DECIMAL(17,0)
  ,LOSS_TYPE_25 DECIMAL(17,0)
  ,LOSS_TYPE_26 DECIMAL(17,0)
  ,LOSS_TYPE_27 DECIMAL(17,0)
  ,LOSS_TYPE_28 DECIMAL(17,0)
  ,LOSS_TYPE_29 DECIMAL(17,0)
  ,LOSS_TYPE_30 DECIMAL(17,0)
  ,FIRE_REPORT_FLG DECIMAL(17,0)
  ,POLICE_REPORT_FLG DECIMAL(17,0)
  ,OFFICIALS_ON_SCENE_FLG DECIMAL(17,0)
  ,WEATHER_AT_LOSS_GOOD DECIMAL(17,0)
  ,WEATHER_AT_LOSS_BAD DECIMAL(17,0)
  ,WEATHER_AT_LOSS_UNKNOWN DECIMAL(17,0)
  ,FAULT_RATING_UNKNOWN DECIMAL(17,0)
  ,FAULT_RATING_OTHER_PARTY DECIMAL(17,0)
  ,FAULT_RATING_COMPARATIVE DECIMAL(17,0)
  ,FAULT_RATING_INSURED DECIMAL(17,0)
  ,FAULT_RATING_NULL DECIMAL(17,0)
  ,BAILMENT_FLG DECIMAL(17,0)
  ,EMERGENCY_TRANSPORT_FLG DECIMAL(17,0)
  ,IN_LITIGATION_FLG DECIMAL(17,0)
  --fields derived from COVERAGE
  ,EXPECTED_SUBRO_AMT DECIMAL(17,0)
  ,SUBRO_CREDITS DECIMAL(17,0)
  ,SUBRO_STATUS_NULL DECIMAL(17,0)
  ,SUBRO_STATUS_CLOSED DECIMAL(17,0)
  ,SUBRO_STATUS_OPEN DECIMAL(17,0)
  ,SUBRO_STATUS_PENDING DECIMAL(17,0)
  ,SUBRO_REFERRAL_FLG_COVERAGE DECIMAL(17,0)
  ,SUBRO_RECOVERY_FLG DECIMAL(17,0)
  ,COVERAGE_PERIL_1 DECIMAL(17,0)
  ,COVERAGE_PERIL_2 DECIMAL(17,0)
  ,COVERAGE_PERIL_3 DECIMAL(17,0)
  ,COVERAGE_PERIL_4 DECIMAL(17,0)
  ,COVERAGE_PERIL_5 DECIMAL(17,0)
  ,COVERAGE_PERIL_6 DECIMAL(17,0)
  ,COVERAGE_PERIL_7 DECIMAL(17,0)
  ,COVERAGE_PERIL_8 DECIMAL(17,0)
  ,COVERAGE_PERIL_9 DECIMAL(17,0)
  ,COVERAGE_PERIL_10 DECIMAL(17,0)
  ,COVERAGE_PERIL_11 DECIMAL(17,0)
  ,COVERAGE_PERIL_12 DECIMAL(17,0)
  ,COVERAGE_PERIL_13 DECIMAL(17,0)
  ,COVERAGE_PERIL_14 DECIMAL(17,0)
  ,COVERAGE_PERIL_15 DECIMAL(17,0)
  ,COVERAGE_PERIL_16 DECIMAL(17,0)
  ,COVERAGE_PERIL_17 DECIMAL(17,0)
  ,COVERAGE_PERIL_18 DECIMAL(17,0)
  ,COVERAGE_PERIL_19 DECIMAL(17,0)
  ,COVERAGE_PERIL_20 DECIMAL(17,0)
);

--Populate ProcessedAutoClaims with data from tables in dl_vsuperus
INSERT INTO dl_T034847.ProcessedAutoClaims
(
  CLAIM_ID
  --fields derived from CLAIM
  ,FILE_TYPE_IS_DEFERRED
  ,FILE_TYPE_IS_REGULAR
  ,FILE_TYPE_IS_SUBROGATION
  ,DAYS_REPORTED_AFTER_LOSS
  ,STATUS_IS_OPEN
  ,STATUS_IS_CLOSED
  ,SUBRO_REFERRAL_FLG
  ,AT_FAULT_FLG
  ,CATASTROPHE_FLG
  ,REPORTED_BY_SELF
  ,REPORTED_BY_CLAIMANT
  ,REPORTED_BY_CHILD
  ,REPORTED_BY_INS_CO
  ,REPORTED_BY_OTHER
  ,REPORTED_BY_SPOUSE
  ,REPORTED_BY_RELATIVE
  ,REPORTED_BY_ATTORNEY
  ,REPORTED_BY_ADV_SUBRO_HNDLR
  ,REPORTED_BY_CLAIMANT_ATTRNY
  ,REPORTED_BY_PARENT
  ,CLAIM_IN_POLICY_STATE
  ,CLAIM_STATE_MA
  ,CLAIM_STATE_TX
  ,CLAIM_STATE_CT
  ,CLAIM_STATE_NY
  ,CLAIM_STATE_FL
  ,CLAIM_STATE_RI
  ,CLAIM_STATE_CA
  ,CLAIM_STATE_NC
  ,CLAIM_STATE_NJ
  ,CLAIM_STATE_GA
  ,CLAIM_STATE_CO
  ,CLAIM_STATE_PA
  ,CLAIM_STATE_NH
  ,CLAIM_STATE_WA
  ,CLAIM_STATE_MD
  ,CLAIM_STATE_AZ
  ,CLAIM_STATE_VA
  ,CLAIM_STATE_OR
  ,CLAIM_STATE_OH
  ,CLAIM_STATE_IL
  ,CLAIM_STATE_MI
  ,CLAIM_STATE_MN
  ,CLAIM_STATE_SC
  ,CLAIM_STATE_TN
  ,CLAIM_STATE_ME
  ,LOSS_TYPE_1
  ,LOSS_TYPE_2
  ,LOSS_TYPE_3
  ,LOSS_TYPE_4
  ,LOSS_TYPE_5
  ,LOSS_TYPE_6
  ,LOSS_TYPE_7
  ,LOSS_TYPE_8
  ,LOSS_TYPE_9
  ,LOSS_TYPE_10
  ,LOSS_TYPE_11
  ,LOSS_TYPE_12
  ,LOSS_TYPE_13
  ,LOSS_TYPE_14
  ,LOSS_TYPE_15
  ,LOSS_TYPE_16
  ,LOSS_TYPE_17
  ,LOSS_TYPE_18
  ,LOSS_TYPE_19
  ,LOSS_TYPE_20
  ,LOSS_TYPE_21
  ,LOSS_TYPE_22
  ,LOSS_TYPE_23
  ,LOSS_TYPE_24
  ,LOSS_TYPE_25
  ,LOSS_TYPE_26
  ,LOSS_TYPE_27
  ,LOSS_TYPE_28
  ,LOSS_TYPE_29
  ,LOSS_TYPE_30
  ,FIRE_REPORT_FLG
  ,POLICE_REPORT_FLG
  ,OFFICIALS_ON_SCENE_FLG
  ,WEATHER_AT_LOSS_GOOD
  ,WEATHER_AT_LOSS_BAD
  ,WEATHER_AT_LOSS_UNKNOWN
  ,FAULT_RATING_UNKNOWN
  ,FAULT_RATING_OTHER_PARTY
  ,FAULT_RATING_COMPARATIVE
  ,FAULT_RATING_INSURED
  ,FAULT_RATING_NULL
  ,BAILMENT_FLG
  ,EMERGENCY_TRANSPORT_FLG
  ,IN_LITIGATION_FLG
  --fields derived from COVERAGE
  ,EXPECTED_SUBRO_AMT
  ,SUBRO_CREDITS
  ,SUBRO_STATUS_NULL
  ,SUBRO_STATUS_CLOSED
  ,SUBRO_STATUS_OPEN
  ,SUBRO_STATUS_PENDING
  ,SUBRO_REFERRAL_FLG_COVERAGE
  ,SUBRO_RECOVERY_FLG
  ,COVERAGE_PERIL_1
  ,COVERAGE_PERIL_2
  ,COVERAGE_PERIL_3
  ,COVERAGE_PERIL_4
  ,COVERAGE_PERIL_5
  ,COVERAGE_PERIL_6
  ,COVERAGE_PERIL_7
  ,COVERAGE_PERIL_8
  ,COVERAGE_PERIL_9
  ,COVERAGE_PERIL_10
  ,COVERAGE_PERIL_11
  ,COVERAGE_PERIL_12
  ,COVERAGE_PERIL_13
  ,COVERAGE_PERIL_14
  ,COVERAGE_PERIL_15
  ,COVERAGE_PERIL_16
  ,COVERAGE_PERIL_17
  ,COVERAGE_PERIL_18
  ,COVERAGE_PERIL_19
  ,COVERAGE_PERIL_20

)
SELECT 
--pull from 'CLAIM' table
  /**CLAIM_ID**/ CLAIM.CLAIM_ID
  ,/**FILE_TYPE_IS_DEFERRED**/ CASE CLAIM.FILE_TYPE WHEN 'Deferred' THEN 1 ELSE 0 END
  ,/**FILE_TYPE_IS_REGULAR**/ CASE CLAIM.FILE_TYPE WHEN 'Regular' THEN 1 ELSE 0 END
  ,/**FILE_TYPE_IS_SUBROGATION**/ CASE CLAIM.FILE_TYPE WHEN 'Subrogation' THEN 1 ELSE 0 END
  ,/**DAYS_REPORTED_AFTER_LOSS**/ CAST(CLAIM.report_dt as date) - CAST(CLAIM.loss_dt as date) 
  ,/**STATUS_IS_OPEN**/ CASE CLAIM.STATUS WHEN 'Open' THEN 1 ELSE 0 END
  ,/**STATUS_IS_CLOSED**/ CASE CLAIM.STATUS WHEN 'Closed' THEN 1 ELSE 0 END
  ,/**SUBRO_REFERRAL_FLG***/ CLAIM.SUBRO_REFERRAL_FLG
  --,SUBRO_REFERRAL_ACCEPTED_FLG = CLAIM.SUBRO_REFERRAL_ACCEPTED_FLG
  ,/**AT_FAULT_FLG**/ CLAIM.AT_FAULT_FLG
  ,/**CATASTROPHE_FLG**/ CLAIM.CATASTROPHE_FLG
  ,/**REPORTED_BY_SELF**/ CASE CLAIM.REPORTED_BY WHEN 'SELF' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_CLAIMANT**/ CASE CLAIM.REPORTED_BY WHEN 'Claimant' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_CHILD**/ CASE CLAIM.REPORTED_BY WHEN 'Child' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_INS_CO**/ CASE CLAIM.REPORTED_BY WHEN 'Claimant''s insurance co.' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_OTHER**/ CASE CLAIM.REPORTED_BY WHEN 'Other' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_SPOUSE**/ CASE CLAIM.REPORTED_BY WHEN 'Spouse' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_RELATIVE**/ CASE CLAIM.REPORTED_BY WHEN 'Relative' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_ATTORNEY**/ CASE CLAIM.REPORTED_BY WHEN 'Attorney' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_ADV_SUBRO_HNDLR**/ CASE CLAIM.REPORTED_BY WHEN 'Adverse Subro Handler' THEN 1 ELSE 0 END
  ,/**REPORTED_BY_CLAIMANT_ATTRNY**/ CASE CLAIM.REPORTED_BY WHEN 'Claimant''s attorney' THEN 1 ELSE 0 END 
  ,/**REPORTED_BY_PARENT**/ CASE CLAIM.REPORTED_BY WHEN 'Parent' THEN 1 ELSE 0 END
  ,/**CLAIM_IN_POLICY_STATE**/ --1 if CLAIM.CLAIM_STATE is the same as POLICY.STATE
  CASE WHEN CLAIM.CLAIM_STATE = POLICY.POLICY_STATE THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_MA**/ CASE CLAIM.CLAIM_STATE WHEN 'MA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_TX**/ CASE CLAIM.CLAIM_STATE WHEN 'TX' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_CT**/ CASE CLAIM.CLAIM_STATE WHEN 'CT' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_NY**/ CASE CLAIM.CLAIM_STATE WHEN 'NY' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_FL**/ CASE CLAIM.CLAIM_STATE WHEN 'FL' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_RI**/ CASE CLAIM.CLAIM_STATE WHEN 'RI' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_CA**/ CASE CLAIM.CLAIM_STATE WHEN 'CA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_NC**/ CASE CLAIM.CLAIM_STATE WHEN 'NC' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_NJ**/ CASE CLAIM.CLAIM_STATE WHEN 'NJ' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_GA**/ CASE CLAIM.CLAIM_STATE WHEN 'GA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_CO**/ CASE CLAIM.CLAIM_STATE WHEN 'CO' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_PA**/ CASE CLAIM.CLAIM_STATE WHEN 'PA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_NH**/ CASE CLAIM.CLAIM_STATE WHEN 'NH' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_WA**/ CASE CLAIM.CLAIM_STATE WHEN 'WA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_MD**/ CASE CLAIM.CLAIM_STATE WHEN 'MD' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_AZ**/ CASE CLAIM.CLAIM_STATE WHEN 'AZ' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_VA**/ CASE CLAIM.CLAIM_STATE WHEN 'VA' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_OR**/ CASE CLAIM.CLAIM_STATE WHEN 'OR' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_OH**/ CASE CLAIM.CLAIM_STATE WHEN 'OH' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_IL**/ CASE CLAIM.CLAIM_STATE WHEN 'IL' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_MI**/ CASE CLAIM.CLAIM_STATE WHEN 'MI' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_MN**/ CASE CLAIM.CLAIM_STATE WHEN 'MN' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_SC**/ CASE CLAIM.CLAIM_STATE WHEN 'SC' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_TN**/ CASE CLAIM.CLAIM_STATE WHEN 'TN' THEN 1 ELSE 0 END
  ,/**CLAIM_STATE_ME**/ CASE CLAIM.CLAIM_STATE WHEN 'ME' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_1**/ CASE CLAIM.LOSS_TYPE WHEN 'Collision with Motor Vehicle' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_2**/ CASE CLAIM.LOSS_TYPE WHEN 'Tow' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_3**/ CASE CLAIM.LOSS_TYPE WHEN 'Rock from Road' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_4**/ CASE CLAIM.LOSS_TYPE WHEN 'Other' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_5**/ CASE CLAIM.LOSS_TYPE WHEN 'Collision with Object' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_6**/ CASE CLAIM.LOSS_TYPE WHEN 'Wind' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_7**/ CASE CLAIM.LOSS_TYPE WHEN 'Rear End Collision' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_8**/ CASE CLAIM.LOSS_TYPE WHEN 'Hit while Parked' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_9**/ CASE CLAIM.LOSS_TYPE WHEN 'Hail' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_10**/ CASE CLAIM.LOSS_TYPE WHEN 'Water Damage' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_11**/ CASE CLAIM.LOSS_TYPE WHEN 'Water Damage (not weather related)' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_12**/ CASE CLAIM.LOSS_TYPE WHEN 'Falling/Flying Objects' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_13**/ CASE CLAIM.LOSS_TYPE WHEN 'Weather Related (ice storm, hurricane, etc.)' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_14**/ CASE CLAIM.LOSS_TYPE WHEN 'Hit and Run' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_15**/ CASE CLAIM.LOSS_TYPE WHEN 'Water Damage (weather related)' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_16**/ CASE CLAIM.LOSS_TYPE WHEN 'Impact with Animal' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_17**/ CASE CLAIM.LOSS_TYPE WHEN 'Malicious Mischief and Vandalism' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_18**/ CASE CLAIM.LOSS_TYPE WHEN 'Burglary/Theft' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_19**/ CASE CLAIM.LOSS_TYPE WHEN 'Snow/Ice' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_20**/ CASE CLAIM.LOSS_TYPE WHEN 'Fire' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_21**/ CASE CLAIM.LOSS_TYPE WHEN 'Freeze' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_22**/ CASE CLAIM.LOSS_TYPE WHEN 'Lost or Mysterious Disappearance' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_23**/ CASE CLAIM.LOSS_TYPE WHEN 'Collision with Person' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_24**/ CASE CLAIM.LOSS_TYPE WHEN 'Theft (entire)' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_25**/ CASE CLAIM.LOSS_TYPE WHEN 'Theft of Parts or Contents' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_26**/ CASE CLAIM.LOSS_TYPE WHEN 'Liability' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_27**/ CASE CLAIM.LOSS_TYPE WHEN 'Flood' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_28**/ CASE CLAIM.LOSS_TYPE WHEN 'Theft (attempted)' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_29**/ CASE CLAIM.LOSS_TYPE WHEN 'Dog Bite/Dangerous Animal' THEN 1 ELSE 0 END
  ,/**LOSS_TYPE_30**/ CASE CLAIM.LOSS_TYPE WHEN 'Collapse/Settlement' THEN 1 ELSE 0 END
  ,/**FIRE_REPORT_FLG**/ CLAIM.FIRE_REPORT_FLG
  ,/**POLICE_REPORT_FLG**/ CASE WHEN CLAIM.POLICE_REPORT_FLG = 1 THEN 1 ELSE 0 END
  ,/**OFFICIALS_ON_SCENE_FLG**/ CASE WHEN CLAIM.OFFICIALS_ON_SCENE_FLG = 1 THEN 1 ELSE 0 END --Can potentially split into 0/1/NULL categories
  ,/**WEATHER_AT_LOSS_GOOD**/ CASE WHEN claim.weather_at_loss like '%clear%' --probably bad for performance
                                or claim.weather_at_loss like '%dry%' THEN 1  ELSE 0 END
  ,/**WEATHER_AT_LOSS_BAD**/ CASE WHEN claim.weather_at_loss like '%hail%'
                                or claim.weather_at_loss like '%wind%'
                                or claim.weather_at_loss like '%rain%'
                                or claim.weather_at_loss like '%snow%' THEN 1 ELSE 0 END
  ,/**WEATHER_AT_LOSS_UNKNOWN**/ CASE WHEN claim.weather_at_loss not like '%hail%'
                                  and claim.weather_at_loss not like '%wind%'
                                  and claim.weather_at_loss not like '%rain%'
                                  and claim.weather_at_loss not like '%snow%'
                                  and claim.weather_at_loss not like '%clear%'
                                  and claim.weather_at_loss not like '%dry%' THEN 1 ELSE 0 END
  ,/**FAULT_RATING_UNKNOWN**/ CASE CLAIM.FAULT_RATING WHEN 'Fault unknown' THEN 1 ELSE 0 END
  ,/**FAULT_RATING_OTHER_PARTY**/ CASE CLAIM.FAULT_RATING WHEN 'Other party at fault' THEN 1 ELSE 0 END
  ,/**FAULT_RATING_COMPARATIVE**/ CASE CLAIM.FAULT_RATING WHEN 'Comparative Fault' THEN 1 ELSE 0 END
  ,/**FAULT_RATING_INSURED**/ CASE CLAIM.FAULT_RATING WHEN 'Insured at fault' THEN 1 ELSE 0 END
  ,/**FAULT_RATING_NULL**/ CASE WHEN CLAIM.FAULT_RATING IS NULL THEN 1 ELSE 0 END
  ,/**BAILMENT_FLG**/ CASE WHEN CLAIM.BAILMENT_FLG = 1 THEN 1 ELSE 0 END
  ,/**EMERGENCY_TRANSPORT_FLG**/ CLAIM.EMERGENCY_TRANSPORT_FLG
  ,/**IN_LITIGATION_FLG**/ CLAIM.IN_LITIGATION_FLG
--pull from 'COVERAGE' table
  ,/**EXPECTED_SUBRO_AMT**/ CASE WHEN COVERAGE.EXPECTED_SUBRO_AMT IS NULL THEN 0 ELSE COVERAGE.EXPECTED_SUBRO_AMT END
  ,/**SUBRO_CREDITS**/ CASE WHEN COVERAGE.SUBRO_CREDITS IS NULL THEN 0 ELSE COVERAGE.SUBRO_CREDITS END
  ,/**SUBRO_STATUS_NULL**/ CASE WHEN COVERAGE.SUBRO_STATUS IS NULL THEN 1 ELSE 0 END
  ,/**SUBRO_STATUS_CLOSED**/ CASE COVERAGE.SUBRO_STATUS WHEN 'Closed' THEN 1 ELSE 0 END
  ,/**SUBRO_STATUS_OPEN**/ CASE COVERAGE.SUBRO_STATUS WHEN 'Open' THEN 1 ELSE 0 END
  ,/**SUBRO_STATUS_PENDING**/ CASE COVERAGE.SUBRO_STATUS WHEN 'Pending' THEN 1 ELSE 0 END
  ,/**SUBRO_REFERRAL_FLG_COVERAGE**/ COVERAGE.SUBRO_REFERRAL_FLG --NOTE: how is this different from CLAIM?
  ,/**SUBRO_RECOVERY_FLG**/ COVERAGE.SUBRO_RECOVERY_FLG
  ,/**COVERAGE_PERIL_1**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Bodily Injury' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_2**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Personal Injury Protection' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_3**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Medical Payments' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_4**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Bodily Injury Reimbursement' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_5**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Underinsured Motorist Bodily Injury' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_6**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Uninsured Motorist Bodily Injury' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_7**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Collision' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_8**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Property Damage' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_9**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Glass' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_10**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Towing and Labor' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_11**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Rental Reimbursement' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_12**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Other' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_13**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Wind' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_14**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Uninsured Motorist Property Damage' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_15**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Malicious Mischief and Vandalism' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_16**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Theft' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_17**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Flood' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_18**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Fire' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_19**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Collision - Limited' THEN 1 ELSE 0 END
  ,/**COVERAGE_PERIL_20**/ CASE COVERAGE.COVERAGE_PERIL WHEN 'Property Protection Insurance' THEN 1 ELSE 0 END

FROM COVERAGE
  INNER JOIN CLAIM --COVERAGE contains 25 claim_ids not in CLAIM, will be removed by inner join
    ON CLAIM.CLAIM_ID = COVERAGE.CLAIM_ID
  LEFT OUTER JOIN POLICY
    ON CLAIM.POLICY_ID = POLICY.POLICY_ID
  WHERE CLAIM.CLAIM_CATEGORY = 'Auto';

  
  /**
  
  database dl_vsuperus;

select 
SUBRO_REFERRAL_FLG, BAILMENT_FLG, count(*)
from claim 
group by SUBRO_REFERRAL_FLG, BAILMENT_FLG order by BAILMENT_FLG, SUBRO_REFERRAL_FLG desc

select 
DUI_FLG, count(*)
from claim 
group by DUI_FLG order by count(*) desc
  
  **/
  
